////////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   / 
// /___/  \  /    Vendor: Xilinx 
// \   \   \/     Version : 3.6
//  \   \         Application : 7 Series FPGAs Transceivers Wizard 
//  /   /         Filename : gt_app_exdes.v
// /___/   /\     
// \   \  /  \ 
//  \___\/\___\ 
//
//
// Module gt_app_exdes
// Generated by Xilinx 7 Series FPGAs Transceivers Wizard
// 
// 
// (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
// 
// This file contains confidential and proprietary information
// of Xilinx, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
// 
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// Xilinx, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) Xilinx shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the
// possibility of the same.
// 
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of Xilinx products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
// 
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES. 


`timescale 1ns / 1ps
`define DLY #1

(* DowngradeIPIdentifiedWarnings="yes" *)
//***********************************Entity Declaration************************
(* CORE_GENERATION_INFO = "gt_app,gtwizard_v3_6_10,{protocol_file=Start_from_scratch}" *)
module gt_app_exdes # (
    parameter       EXAMPLE_CONFIG_INDEPENDENT_LANES     =   1            ,   // configuration for frame gen and check
    parameter       EXAMPLE_LANE_WITH_START_CHAR         =   0            ,   // specifies lane with unique start frame char
    parameter       EXAMPLE_WORDS_IN_BRAM                =   512          ,   // specifies amount of data in BRAM
    parameter       EXAMPLE_SIM_GTRESET_SPEEDUP          =   "TRUE"       ,   // simulation setting for GT SecureIP model
    parameter       EXAMPLE_USE_CHIPSCOPE                =   0            ,   // Set to 1 to use Chipscope to drive resets
    parameter       STABLE_CLOCK_PERIOD                  =   10
) (
    input  wire     Q0_CLK0_GTREFCLK_PAD_N_IN   ,
    input  wire     Q0_CLK0_GTREFCLK_PAD_P_IN   ,
    input  wire     DRP_CLK_IN_P                ,
    input  wire     DRP_CLK_IN_N                ,
    output wire     TXN_OUT                     ,
    output wire     TXP_OUT
);

//**************************** Wire Declarations ******************************//
    //------------------------ GT Wrapper Wires ------------------------------
    //________________________________________________________________________
    //________________________________________________________________________
    //GT0  (X1Y0)
    //------------------------- Digital Monitor Ports --------------------------
    wire    [7:0]   gt0_dmonitorout_i       ;
    //------------------------ RX Margin Analysis Ports ------------------------
    wire            gt0_eyescandataerror_i  ;
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    wire    [6:0]   gt0_rxmonitorout_i      ;
    wire    [1:0]   gt0_rxmonitorsel_i      ;
    //------------------- TX Initialization and Reset Ports --------------------
    wire            gt0_gttxreset_i         ;
    wire            gt0_txuserrdy_i         ;
    //---------------- Transmit Ports - TX Data Path interface -----------------
    wire    [31:0]  gt0_txdata_i            ;
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    wire            gt0_gtxtxn_i            ;
    wire            gt0_gtxtxp_i            ;
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    wire            gt0_txoutclk_i          ;
    wire            gt0_txoutclkfabric_i    ;
    wire            gt0_txoutclkpcs_i       ;
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    wire            gt0_txresetdone_i       ;

    //----------------------------- Global Signals -----------------------------
    wire            drpclk_in_i             ;
    wire            DRPCLK_IN               ;
    wire            gt0_tx_system_reset_c   ;

    //--------------------------- User Clocks ---------------------------------
    wire            gt0_txusrclk_i          ; 
    wire            gt0_txusrclk2_i         ; 
    wire            gt0_txmmcm_lock_i       ;

    //--------------------- Frame check/gen Module Signals --------------------
    wire    [15:0]  gt0_txdata_float16_i    ;
    wire    [31:0]  gt0_txdata_float_i      ;
  
    gt_app_support # (
        .EXAMPLE_SIM_GTRESET_SPEEDUP    (EXAMPLE_SIM_GTRESET_SPEEDUP),
        .STABLE_CLOCK_PERIOD            (STABLE_CLOCK_PERIOD        )
    ) gt_app_support_i (        
        .soft_reset_tx_in               (1'b0                       ),
        .dont_reset_on_data_error_in    (1'b0                       ),
        .q0_clk0_gtrefclk_pad_n_in      (Q0_CLK0_GTREFCLK_PAD_N_IN  ),
        .q0_clk0_gtrefclk_pad_p_in      (Q0_CLK0_GTREFCLK_PAD_P_IN  ),
        .gt0_tx_mmcm_lock_out           (gt0_txmmcm_lock_i          ),
        .gt0_tx_fsm_reset_done_out      (gt0_txfsmresetdone_i       ),
        .gt0_rx_fsm_reset_done_out      (gt0_rxfsmresetdone_i       ),
        .gt0_data_valid_in              (1'b0                       ),
 
        .gt0_txusrclk_out               (gt0_txusrclk_i             ),
        .gt0_txusrclk2_out              (gt0_txusrclk2_i            ),

        //-------------------------- Channel - DRP Ports  --------------------------
        .gt0_drpaddr_in                 (9'd0                       ), 
        .gt0_drpdi_in                   (16'd0                      ),
        .gt0_drpdo_out                  (                           ),
        .gt0_drpen_in                   (1'b0                       ),
        .gt0_drprdy_out                 (                           ),
        .gt0_drpwe_in                   (1'b0                       ),
        //------------------------- Digital Monitor Ports --------------------------
        .gt0_dmonitorout_out            (gt0_dmonitorout_i          ),
        //------------------- RX Initialization and Reset Ports --------------------
        .gt0_eyescanreset_in            (1'b0                       ),
        //------------------------ RX Margin Analysis Ports ------------------------
        .gt0_eyescandataerror_out       (gt0_eyescandataerror_i     ),
        .gt0_eyescantrigger_in          (1'b0                       ),
        //------------------- Receive Ports - RX Equalizer Ports -------------------
        .gt0_rxmonitorout_out           (gt0_rxmonitorout_i         ),
        .gt0_rxmonitorsel_in            (2'b00                      ),
        //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .gt0_gtrxreset_in               (1'b0                       ),
        //------------------- TX Initialization and Reset Ports --------------------
        .gt0_gttxreset_in               (1'b0                       ),
        .gt0_txuserrdy_in               (1'b1                       ),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .gt0_txdata_in                  (gt0_txdata_i               ),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .gt0_gtxtxn_out                 (TXN_OUT                    ),
        .gt0_gtxtxp_out                 (TXP_OUT                    ),
        //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .gt0_txoutclkfabric_out         (gt0_txoutclkfabric_i       ),
        .gt0_txoutclkpcs_out            (gt0_txoutclkpcs_i          ),
        //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .gt0_txresetdone_out            (gt0_txresetdone_i          ),
        //--------------- Transmit Ports - TX Polarity Control Ports ---------------
        .gt0_txpolarity_in              (1'b0                       ),

    //____________________________COMMON PORTS________________________________
        .gt0_qplllock_out               (                           ),
        .gt0_qpllrefclklost_out         (                           ),
        .gt0_qplloutclk_out             (                           ),
        .gt0_qplloutrefclk_out          (                           ),
        .sysclk_in                      (drpclk_in_i                )
    );
    
    always @(posedge  gt0_txusrclk2_i or negedge gt0_txfsmresetdone_i) begin
        if (!gt0_txfsmresetdone_i) begin
            gt0_txfsmresetdone_r    <=   `DLY 1'b0;
            gt0_txfsmresetdone_r2   <=   `DLY 1'b0;
        end
        else begin
            gt0_txfsmresetdone_r    <=   `DLY gt0_txfsmresetdone_i;
            gt0_txfsmresetdone_r2   <=   `DLY gt0_txfsmresetdone_r;
        end
    end

    IBUFDS IBUFDS_DRP_CLK (
        .I  (DRP_CLK_IN_P   ),
        .IB (DRP_CLK_IN_N   ),
        .O  (DRPCLK_IN      )
    );

    BUFG DRP_CLK_BUFG (
        .I  (DRPCLK_IN      ),
        .O  (drpclk_in_i    ) 
    );

    gt_app_GT_FRAME_GEN # (
        .WORDS_IN_BRAM(EXAMPLE_WORDS_IN_BRAM)
    ) gt0_frame_gen (
        .TX_DATA_OUT  ({gt0_txdata_float_i,gt0_txdata_i,gt0_txdata_float16_i}),
        .TXCTRL_OUT   (),
        .USER_CLK     (gt0_txusrclk2_i      ),
        .SYSTEM_RESET (gt0_tx_system_reset_c)
    );


assign gt0_tx_system_reset_c    = !gt0_txfsmresetdone_r2;



endmodule
    

