######################################################################
#
# File name : gt_app_TB_wave.do
# Created on: Wed Jun 03 20:54:32 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
