######################################################################
#
# File name : gt_app_TB_simulate.do
# Created on: Wed Jun 17 11:38:11 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.gt_app_TB xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {gt_app_TB_wave.do}

view wave
view structure
view signals

do {gt_app_TB.udo}

run 1000ns
