######################################################################
#
# File name : gt_app_TB_wave.do
# Created on: Sun Jun 14 19:46:59 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
