######################################################################
#
# File name : gt_app_TB_compile.do
# Created on: Wed Jun 03 20:54:30 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.7\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.7\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.7\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../gt_app_ex.srcs/sources_1/ip/gt_app/gt_app/example_design/gt_app_tx_startup_fsm.v" \
"../../../../gt_app_ex.srcs/sources_1/ip/gt_app/gt_app/example_design/gt_app_rx_startup_fsm.v" \
"../../../../gt_app_ex.srcs/sources_1/ip/gt_app/gt_app_init.v" \
"../../../../gt_app_ex.srcs/sources_1/ip/gt_app/gt_app_gt.v" \
"../../../../gt_app_ex.srcs/sources_1/ip/gt_app/gt_app_multi_gt.v" \
"../../../../gt_app_ex.srcs/sources_1/ip/gt_app/gt_app/example_design/gt_app_sync_block.v" \
"../../../../gt_app_ex.srcs/sources_1/ip/gt_app/gt_app.v" \
"../../../../gt_app_ex.srcs/sources_1/imports/example_design/support/gt_app_clock_module.v" \
"../../../../gt_app_ex.srcs/sources_1/imports/example_design/support/gt_app_common.v" \
"../../../../gt_app_ex.srcs/sources_1/imports/example_design/support/gt_app_common_reset.v" \
"../../../../gt_app_ex.srcs/sources_1/imports/example_design/gt_app_exdes.v" \
"../../../../gt_app_ex.srcs/sources_1/imports/example_design/gt_app_gt_frame_gen.v" \
"../../../../gt_app_ex.srcs/sources_1/imports/example_design/support/gt_app_gt_usrclk_source.v" \
"../../../../gt_app_ex.srcs/sources_1/imports/example_design/support/gt_app_support.v" \
"../../../../gt_app_ex.srcs/sources_1/ip/rx_gt_app/rx_gt_app/example_design/support/rx_gt_app_common.v" \
"../../../../gt_app_ex.srcs/sources_1/ip/rx_gt_app/rx_gt_app/example_design/support/rx_gt_app_common_reset.v" \
"../../../../gt_app_ex.srcs/sources_1/ip/rx_gt_app/rx_gt_app/example_design/rx_gt_app_exdes.v" \
"../../../../gt_app_ex.srcs/sources_1/ip/rx_gt_app/rx_gt_app/example_design/rx_gt_app_gt_frame_check.v" \
"../../../../gt_app_ex.srcs/sources_1/ip/rx_gt_app/rx_gt_app/example_design/support/rx_gt_app_gt_usrclk_source.v" \
"../../../../gt_app_ex.srcs/sources_1/ip/rx_gt_app/rx_gt_app_sim_netlist.v" \
"../../../../gt_app_ex.srcs/sources_1/ip/rx_gt_app/rx_gt_app/example_design/support/rx_gt_app_support.v" \
"../../../../gt_app_ex.srcs/sim_1/imports/simulation/gt_app_tb.v" \


# compile glbl module
C:\\modeltech64_10.7\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

