# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Administrator/Desktop/GT/gt_app/gt_app.srcs/sources_1/ip/gt_app/gt_app.xci
# IP: The module: 'gt_app' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/GT/gt_app/gt_app.srcs/sources_1/ip/gt_app/gt_app.xdc
# XDC: The top module name and the constraint reference have the same name: 'gt_app'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Administrator/Desktop/GT/gt_app/gt_app.srcs/sources_1/ip/gt_app/gt_app_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gt_app'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Administrator/Desktop/GT/gt_app/gt_app.srcs/sources_1/ip/gt_app/gt_app.xci
# IP: The module: 'gt_app' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/GT/gt_app/gt_app.srcs/sources_1/ip/gt_app/gt_app.xdc
# XDC: The top module name and the constraint reference have the same name: 'gt_app'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Administrator/Desktop/GT/gt_app/gt_app.srcs/sources_1/ip/gt_app/gt_app_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gt_app'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
